### ISSUE TITLE
Special case blocks.

### ISSUE THREAD

**Issue by Claycorp** [CCM-Modding/Compresstion#12]
A simple way for me or someone else to add in specialty blocks. Like compressed coal burns longer or compressed redstone is stronger... ETC

If you want to be a lazy butt then its not a big deal just thought it would be nice.

**Comment by TuxCraft** [comment]
_upvote_ :+1:

Going off the compressed redstone is stronger thing, is it possible to emit a redstone signal greater than 15?

**Comment by CaptainShadows** [comment]
I don't think so
