### ISSUE TITLE
Uhhh yeahh...

### ISSUE THREAD

**Issue by Claycorp** [CCM-Modding/Compresstion#18]
http://imgur.com/a/KS3Pz

HOW DO YOU FUCK UP NUMBERS XD??!?!? 
Decuple and up uses the same number.....

**Comment by CaptainShadows** [comment]
BECAUSE THAT IS INTEGER.MAXVALUE!

**Comment by Claycorp** [comment]
You really couldn't write it out... with the rest of the string???? Lazy ass...

**Comment by CaptainShadows** [comment]
... not the way I'm doing it. BECAUSE THAT WOULD BE NEARLY IMPOSSIBLE! but I can switch it to a long which is 2^63 -1 instead of 2^31 -1. And yes I do know those values of the top of my head :P

**Comment by Claycorp** [comment]
you are an AWESOME...

**Comment by Claycorp** [comment]
Just fix it cause theres no point in having it if you don't have the correct numbers you twat...
